name: Test

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Clean up
              run: |
                sudo apt list --installed

            - name: System information
              run: cat /etc/os-release